### ISSUE TITLE
[RFE] Check kubelet

### ISSUE THREAD

**Issue by e-minguez** [RHsyseng/openshift-checks#64]
Something like `curl -k -H "Authorization: Bearer $(oc whoami -t)" https://10.19.138.32:10250/stats/summary` or any other kubelet api endpoint that can be helpful (see https://github.com/cyberark/kubeletctl & https://github.com/cyberark/kubeletctl/blob/master/API_TABLE.md )

**Comment by iranzo** [comment]
Close via https://github.com/RHsyseng/openshift-checks/pull/67 ? @dcritch

**Comment by dcritch** [comment]
WFH.
